function operacao() {
    
}

try{}

catch (error){
    console.log("Ocorreu um erro.", error.message)
}